### ISSUE TITLE
WP cli not getting installed ?

### ISSUE THREAD

**Issue by altan-me** [greenpeace/planet4-base#35]
Hi there, 
should composer be installing "wp-cli" itself or is this a dependency needing manual install
(see screenshot)
![screenshot from 2018-04-30 10-36-19](https://user-images.githubusercontent.com/12891722/39411662-9ae5666c-4c62-11e8-9116-272fc5bfbee0.png)

**Comment by 27Bslash6** [comment]
wp-cli is an external pre-requisite at the moment. This is due to how the docker and, I believe, puppet configurations manage permissions.
